version: '{build}'

image: Visual Studio 2019

platform: Any CPU

cache: packages\

before_build:
- cmd: nuget restore
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -ne "true") {
      $env:CONFIGURATION="Debug"
    } else {
      $env:CONFIGURATION="Release"
    }

build:
  verbosity: normal

before_deploy:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      Push-AppveyorArtifact .\src\MLauncher\bin\$env:CONFIGURATION\MLauncher.exe -DeploymentName deployment
      Push-AppveyorArtifact .\src\MLauncher\bin\$env:CONFIGURATION\MLauncher.zip -DeploymentName deployment
    }

artifacts:
- path: \src\MLauncher\bin\$(CONFIGURATION)\MLauncher.exe

deploy:
  provider: GitHub
  auth_token:
    secure: 7cnsqpVwcTuOaXbhv/wDjIFz/4J/9otXf3TqbI3ExgoRU5kwB1JUuqrCrYmkJFXO
  artifact: deployment
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true