version: '{build}'

image: Visual Studio 2019

platform: Any CPU

cache: packages\

before_build:
- cmd: nuget restore
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -ne "true") {
      $env:CONFIGURATION="Debug"
    } else {
      $env:CONFIGURATION="Release"
    }

build:
  verbosity: normal

before_deploy:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      Push-AppveyorArtifact .\src\MLauncher\bin\$env:CONFIGURATION\MLauncher.exe -DeploymentName deployment
      Push-AppveyorArtifact .\src\MLauncher\bin\$env:CONFIGURATION\MLauncher.zip -DeploymentName deployment
    }

artifacts:
- path: \src\MLauncher\bin\$(CONFIGURATION)\MLauncher.exe

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 0c047019ba698391f907bc6f2808c0095c7c3111 # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
